### ISSUE TITLE
Vercel access to page got 404

### ISSUE THREAD

**Issue by kossa** [ahmedh01/starter-template#2]
Hello,

Thank you for your stater I used it for a project: https://lwaten.vercel.app/

In the menu when I click on any item it show /category page, but if you reload the page or send the link you'll get 404 page

My router/index.js file
```

import { createRouter, createWebHistory } from 'vue-router'

const routes = [
    {
        path: '/',
        name: 'Home',
        component: () => import("../pages/Home.vue")
    },
    {
        path: '/article',
        name: 'Article',
        component: () => import("../pages/Article.vue")
    },
    {
        path: '/category',
        name: 'Category',
        component: () => import("../pages/Category.vue")
    }
]

const router = createRouter({
    history: createWebHistory(),
    routes,
})

export default router

```

**Comment by ahmedh01** [comment]
I ran into a similar thing for when I wanted to set a Nav Item to `active` based on the route. In my case, the problem was that if you are refreshing the browser tab, or visiting the link directly, it will not have the necessary `prop` information.

To solve for this, I used the following logic:

```
const navigation = ['Nav Link 1', 'Nav Link 2', 'Nav Link 3', 'Nav Link 4']
const router = useRouter()

// set the active state of nav links based on which route we're on
function getActiveIndex() {
    const index = navigation.findIndex(
        (item) => item === router.currentRoute.value.name
    )
    if (index >= 0) return index
    else return ''
}
// active state handler for nav items
const activeIndex = ref(getActiveIndex()) // initialize on first run
// watch for the route to change and update the active state of the nav item accordingly
watch(router.currentRoute, (newRoute) => {
    activeIndex.value = getActiveIndex()
})
```

Basically, you want to check to see if you have the available information from the route in order to handle the logic in your page. If not, you want to initialize it using `router.currentRoute.value`

Hope this helps.

**Comment by kossa** [comment]
Th main problem is not with the active state but the page access, I cannot access for example to https://lwaten.vercel.app/category

But in https://lwaten.vercel.app/ if you click on any item in the menu you'll be in https://lwaten.vercel.app/category

**Comment by ahmedh01** [comment]
Yes, I understand -- the active state was an example of a similar issue, not the exact same issue. The problem you are facing is not with the starter template itself, but with the understanding and/or knowledge about Vue 3 and Vue Router and how they work. I gave you some insight on what line of thinking to pursue. The rest is up to you.

Since this is not an issue with the code associated with this code repository, I'll be closing this thread. I suggest Stack Overflow.
